import type { Locale } from "@/lib/i18n";

export function healthText(locale: Locale) {
  return locale === "en"
    ? {
        generatedAt: "Generated",
        overall: "Overall status",
        ok: "Healthy",
        warning: "Needs attention",
        critical: "Action required",
        database: "Database",
        runtime: "Runtime",
        directories: "Runtime directories",
        backup: "Backup",
        queues: "Queues",
        mail: "Mail",
        security: "Security",
        configured: "Configured",
        connected: "Connected",
        failed: "Failed",
        source: "Source",
        host: "Host",
        port: "Port",
        databaseName: "Database",
        user: "User",
        password: "Password",
        missingEnv: "Missing MYSQL env",
        latency: "Latency",
        path: "Path",
        exists: "Exists",
        writable: "Writable",
        entries: "Entries",
        schedule: "Schedule",
        enabled: "Enabled",
        disabled: "Disabled",
        frequency: "Frequency",
        time: "Time",
        retention: "Retention",
        lastRun: "Last run",
        lastStatus: "Last status",
        latestBackup: "Latest backup",
        failedLast7Days: "Failed in 7 days",
        articleQueue: "Article translation",
        publicQueue: "Public content translation",
        activeQueues: "Active",
        queueIssues: "Issues",
        queued: "Queued",
        running: "Running",
        failedJobs: "Failed",
        staleRunning: "Stale running",
        notifications: "Notifications",
        ready: "Ready",
        sender: "Sender",
        failedMail: "Failed in 24h",
        skippedMail: "Skipped in 24h",
        activeAdmins: "Active admins",
        disabledAdmins: "Disabled admins",
        activeSessions: "Active sessions",
        trustedDevices: "Trusted devices",
        failOpen: "SMTP fail-open logins",
        recentLogins: "Recent logins",
        nodeEnv: "Node env",
        nodeVersion: "Node version",
        timezone: "Timezone",
        workerMode: "Worker mode",
        workerRole: "Worker role",
        inProcessWorkers: "In-process workers",
        yes: "Yes",
        no: "No",
        none: "None",
        unavailable: "Unavailable",
        never: "Never",
        daySuffix: "days"
      }
    : {
        generatedAt: "生成时间",
        overall: "整体状态",
        ok: "健康",
        warning: "需要关注",
        critical: "需要处理",
        database: "数据库",
        runtime: "运行环境",
        directories: "运行目录",
        backup: "备份",
        queues: "队列",
        mail: "邮件",
        security: "安全",
        configured: "已配置",
        connected: "已连接",
        failed: "失败",
        source: "来源",
        host: "主机",
        port: "端口",
        databaseName: "数据库",
        user: "用户",
        password: "密码",
        missingEnv: "缺少 MYSQL 环境变量",
        latency: "延迟",
        path: "路径",
        exists: "存在",
        writable: "可写",
        entries: "条目数",
        schedule: "计划",
        enabled: "启用",
        disabled: "停用",
        frequency: "频率",
        time: "时间",
        retention: "保留",
        lastRun: "上次执行",
        lastStatus: "上次状态",
        latestBackup: "最新备份",
        failedLast7Days: "7 天失败数",
        articleQueue: "文章翻译",
        publicQueue: "公共内容翻译",
        activeQueues: "活跃",
        queueIssues: "异常",
        queued: "排队",
        running: "运行中",
        failedJobs: "失败",
        staleRunning: "停滞运行",
        notifications: "通知",
        ready: "就绪",
        sender: "发件配置",
        failedMail: "24 小时失败",
        skippedMail: "24 小时跳过",
        activeAdmins: "启用站长",
        disabledAdmins: "停用站长",
        activeSessions: "有效会话",
        trustedDevices: "信任设备",
        failOpen: "SMTP 失败放行登录",
        recentLogins: "最近登录",
        nodeEnv: "Node 环境",
        nodeVersion: "Node 版本",
        timezone: "时区",
        workerMode: "Worker 模式",
        workerRole: "Worker 角色",
        inProcessWorkers: "进程内 Worker",
        yes: "是",
        no: "否",
        none: "无",
        unavailable: "不可用",
        never: "从未",
        daySuffix: "天"
      };
}

export type HealthText = ReturnType<typeof healthText>;
