-- AlterEnum
ALTER TABLE `VerificationCode`
  MODIFY `type` ENUM('REGISTER', 'LOGIN', 'RESET_PASSWORD', 'TOTP_DISABLE') NOT NULL;

ALTER TABLE `MailTemplate`
  MODIFY `scene` ENUM('MOMENT_COMMENT', 'LOGIN_ALERT', 'LOGIN_CODE', 'TOTP_DISABLE_CODE', 'TOTP_RECOVERY_USED', 'COMMENT_REPLY', 'EMAIL_VERIFY', 'PASSWORD_RESET', 'CUSTOM_PAGE_COMMENT', 'ARTICLE_COMMENT', 'GUESTBOOK_REPLY', 'REGISTER_CODE') NOT NULL;

ALTER TABLE `MailSendLog`
  MODIFY `scene` ENUM('MOMENT_COMMENT', 'LOGIN_ALERT', 'LOGIN_CODE', 'TOTP_DISABLE_CODE', 'TOTP_RECOVERY_USED', 'COMMENT_REPLY', 'EMAIL_VERIFY', 'PASSWORD_RESET', 'CUSTOM_PAGE_COMMENT', 'ARTICLE_COMMENT', 'GUESTBOOK_REPLY', 'REGISTER_CODE') NOT NULL;
